site_name: LeetCode Daily
site_url: https://cliffchaff.github.io/leetcode-daily/
site_description: Daily LeetCode problem solutions with detailed explanations
site_author: Cliffchaff

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Solutions:
      - 2024:
          - January: 2024/01/index.md
          - February: 2024/02/index.md
          - March: 2024/03/index.md
          - April: 2024/04/index.md
          - May: 2024/05/index.md
          - June: 2024/06/index.md
          - July: 2024/07/index.md
          - August: 2024/08/index.md
          - September: 2024/09/index.md
          - October: 2024/10/index.md
          - November: 2024/11/index.md
          - December: 2024/12/index.md
  - About: about.md

plugins:
  - search
  - awesome-pages
  - tags

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true

repo_url: https://github.com/cliffchaff/leetcode-daily
repo_name: cliffchaff/leetcode-daily

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cliffchaff
